version: "3.9"
services:
  db:
    image: mysql:latest
    container_name: base_datos
    environment:
      - MYSQL_DATABASE=taller
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.db
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  web:
    container_name: servidor-web
    build: 
      context: .
      dockerfile: ./www/Dockerfile
    volumes:
      #Mapeo de la carpeta www, todo lo relacionado al servidor-web va en esta carpeta
      - ./www:/var/www/html
    ports:
      - 8000:80
volumes:
  db-dump:
  mysql:
  www:

    